# BackPropagation on One-Step

In [1]:
import torch

In [2]:
x = torch.tensor(2.0, requires_grad=True) # Computational tracking on the tensor.

In [3]:
x

tensor(2., requires_grad=True)

In [4]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [6]:
y.backward() # BackPropagtion

In [7]:
print(x.grad)

tensor(93.)


# BackPropagation on Multi-Step

In [17]:
x = torch.tensor([[1.,2,3],[3,2,1]], requires_grad=True)
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [18]:
y = 3*x + 2 # First Layer
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [19]:
z = 2*y**2 # Second Layer
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [20]:
out = z.mean()
out

tensor(140., grad_fn=<MeanBackward0>)

In [21]:
out.backward() # Find Gradient of W.R.T x 
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
